# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            E-commerce at scale Meetup Dublin
tagline:          'An e-commerce meetup by people doing e-commerce'
description:      'An e-commerce meetup by people doing e-commerce.'
url:              ecommerce-meetup.github.io
baseurl:          /

author:
  name:           'Arthur Thevenet'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0


twitter:          https://twitter.com/EcomAtScale
meetup:           https://www.meetup.com/e-commerce-at-scale/
github:
  repo:           https://github.com/ecommerce-meetup

relative_permalinks: false

gems:
  - jekyll-paginate
  - redcarpet